########################################################################################################################
# Copyright 2021 the authors (see AUTHORS file for full list).                                                         #
#                                                                                                                      #
# This file is part of OpenCMP.                                                                                        #
#                                                                                                                      #
# OpenCMP is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public  #
# License as published by the Free Software Foundation, either version 2.1 of the License, or (at your option) any     #
# later version.                                                                                                       #
#                                                                                                                      #
# OpenCMP is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied        #
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more  #
# details.                                                                                                             #
#                                                                                                                      #
# You should have received a copy of the GNU Lesser General Public License along with OpenCMP. If not, see             #
# <https://www.gnu.org/licenses/>.                                                                                     #
########################################################################################################################

"""
Two-fluid model with a phase energy equation for each phase.

For each phase k (c: continuous/liquid, d: dispersed/gas) a temperature T_k is transported, written in
non-conservative (temperature) form and divided by the constant rho_k*cp_k:

    A_k (dT_k/dt + u_k . grad T_k) = div(A_k kappa_k grad T_k) + Q_ik/(rho_k cp_k) + S_k

    kappa_k = k_k/(rho_k cp_k)
    Q_ic    = h_i a_i (T_d - T_c),  Q_id = -Q_ic          (interphase sensible heat exchange)
    S_d     = mdot (T_sat - T_d)                         (gas created by the gas sources enters at T_sat)

This is the conservative form d(A_k T_k)/dt + div(A_k u_k T_k) minus T_k times the phase continuity equation. The
continuity part is discretized with the same upwind DG operator as the advection, so a uniform temperature stays
uniform independently of how TwoFluidModel discretizes alpha_c and the mixture continuity (a purely conservative
form turns any mismatch between those discretizations into spurious heating/cooling). Energy is then conserved up
to the discretization error of the phase continuity.

The phase fractions are lagged (old time level in the storage term, Picard iterate elsewhere). A small
regularization epsilon is added to the phase fraction in the storage and diffusion terms so that T_k stays defined
where phase k is absent.

Both temperatures use L2 (DG) spaces: upwind advective fluxes, SIPG diffusion.

Boundary conditions:
    - Walls (u_k.n = 0) are adiabatic unless given a heat flux in [NEUMANN] (W/m^2 into the domain, applied to
      the equation of the phase it is given for).
    - Open (ZERO_STRESS) boundaries of u_k: outflow advects T_k out; backflow enters as pure liquid at
      T_backflow.

Parameters are read from the [ENERGY] section of model_dir/model_config:
    cp_c, cp_d           specific heats [J/kg/K]
    k_c, k_d             thermal conductivities [W/m/K]
    T_sat                saturation temperature [K]
    T_backflow           temperature of liquid entering through open boundaries [K], default T_sat
    epsilon              phase fraction regularization, default 1e-3
    interphase_heat_transfer = RanzMarshall | none, default RanzMarshall

TODO: physics to consider adding
    - Boussinesq buoyancy in the liquid momentum equation, rho_c beta (T_c - T_ref) g, for natural convection.
    - Interphase mass transfer: condensation of vapor in subcooled liquid (and evaporation in superheated liquid),
      with the latent heat going to the liquid and a gas volume sink/source in alpha_c and the mixture continuity.
    - Latent heat of the gas generated by the gas sources, as an alternative to removing it from the wall flux.
    - Temperature-dependent properties (rho, cp, k, nu, sigma), in particular for subcooled conditions.
    - Viscous dissipation and pressure work (negligible for pool boiling).
    - Turbulent / bubble-induced heat diffusivity.
    - Momentum of the gas created by the gas sources in the dispersed-phase momentum equation. The [INJECTION] source
      doesn't have it; the time-spreading branch of the TFM-automata coupling adds it to its heater source as
      [HEATER] vapor_rise_velocity (coupling/tfm_coupled.py there).
    - Parallel runs with MPI (not physics). OpenCMP has no MPI support: load_mesh gives every rank the whole mesh (no
      Distribute), and the direct solvers (PARDISO, UMFPACK) are serial. Needed: a distributed mesh, a parallel linear
      solver (MUMPS, or PETSc through ngsPETSc; the pip NGSolve build has neither), and a check that the DG face terms
      assemble correctly across subdomains. The TFM-automata coupling manager would then map the automata's
      per-column data to and from the distributed elements through a column-element table built once at the start,
      with the automata running serially on one rank.
"""

import logging
from typing import Dict, List, Optional, Union

import ngsolve as ngs
from ngsolve import GridFunction, FESpace, Parameter
from ngsolve.comp import ProxyFunction

from .tfm import TwoFluidModel
from ..helpers.dg import avg, jump, weighted_grad_avg
from ..helpers.math import Max, Min


class TwoFluidModelEnergy(TwoFluidModel):
    """
    TwoFluidModel with liquid and gas temperature equations, both in L2 spaces. The temperatures are the
    model components t_c and t_d (lower case, like the other variables, since config option names are
    lower-cased).
    """

    ENERGY_COMPONENTS = ('t_c', 't_d')
    INTERPHASE_HEAT_TRANSFER_MODELS = ('RanzMarshall', 'none')
    BC_VARIABLES = dict(TwoFluidModel.BC_VARIABLES, neumann=('t_c', 't_d'))

    # ------------------------------------------------------------------
    # Bookkeeping
    # ------------------------------------------------------------------

    def _define_model_components(self) -> Dict[str, Optional[int]]:
        components = super()._define_model_components()
        n = len(components)
        components.update({'t_c': n, 't_d': n + 1})
        return components

    def _define_model_local_error_components(self) -> Dict[str, bool]:
        return dict(super()._define_model_local_error_components(), t_c=True, t_d=True)

    def _define_time_derivative_components(self) -> List[Dict[str, bool]]:
        # The energy storage terms are phase-fraction weighted, so they are added in time_derivative_terms
        # instead of the default T*v terms.
        return [dict(forms, t_c=False, t_d=False) for forms in super()._define_time_derivative_components()]

    def _define_bc_types(self) -> List[str]:
        return super()._define_bc_types() + ['neumann']

    def _construct_fes(self) -> FESpace:
        for name in self.ENERGY_COMPONENTS:
            if self.element[name] != 'L2':
                raise ValueError("TwoFluidModelEnergy requires an L2 element for '{}', got '{}'."
                                 .format(name, self.element[name]))

        spaces = list(super()._construct_fes().components)
        scalar_ord = max(self.interp_ord - 1, 0)
        fes_T = [ngs.L2(self.mesh, order=scalar_ord, dgjumps=self.DG) for _ in self.ENERGY_COMPONENTS]
        # Insert right after alpha_c so the optional mean-zero-pressure NumberSpace stays last (it is accessed as
        # U[-1]/V[-1] in the TwoFluidModel forms).
        n = self.model_components['t_c']
        spaces[n:n] = fes_T
        return FESpace(spaces, dgjumps=self.DG)

    # ------------------------------------------------------------------
    # Linear solves
    # ------------------------------------------------------------------

    def linear_solve(self, a_assembled, L_assembled, precond, gfu) -> None:
        """
        Direct solves with PARDISO reuse the factorization object between Picard iterations and time steps.

        The base implementation builds a new a.mat.Inverse() for every Picard iteration, repeating the symbolic
        analysis and reordering although the sparsity pattern of the assembled matrix never changes. On the pool
        boiling mesh that set-up is about 1 s of serial work per iteration, as much as the assembly. Here the inverse
        is built once per bilinear form and afterwards only refactorized with Update(), which gives the same factors
        at a fifth of the cost. Assemble() refills the same matrix object, so Update() sees the new values; a different
        matrix or set of free dofs gets a new inverse. Other linear solvers use the base implementation.
        """
        if self.linear_solver != 'direct' or not (ngs.config.USE_PARDISO or ngs.config.USE_MKL):
            return super().linear_solve(a_assembled, L_assembled, precond, gfu)
        if precond is None and self.no_constrained_dofs:
            raise ValueError('Must constrain Dirichlet DOFs if not providing a preconditioner.')

        mat, freedofs = a_assembled.mat, self.fes.FreeDofs()
        inverses = self.__dict__.setdefault('_direct_inverses', {})
        cached = inverses.get(id(a_assembled))
        if cached is not None and cached[0] is mat and cached[1] is freedofs:
            inv = cached[2]
            inv.Update()
        else:
            inv = mat.Inverse(freedofs=freedofs, inverse='pardiso')
            inverses[id(a_assembled)] = (mat, freedofs, inv)

        r = L_assembled.vec.CreateVector()
        r.data = L_assembled.vec - mat * gfu.vec
        gfu.vec.data += inv * r

    # ------------------------------------------------------------------
    # Parameters
    # ------------------------------------------------------------------

    def _set_model_parameters(self) -> None:
        super()._set_model_parameters()

        model_config = self.model_functions.config
        if not model_config.has_section('ENERGY'):
            raise ValueError('TwoFluidModelEnergy requires an [ENERGY] section in model_dir/model_config.')

        allowed = {'cp_c', 'cp_d', 'k_c', 'k_d', 't_sat', 't_backflow', 'epsilon', 'interphase_heat_transfer'}
        unknown = set(model_config['ENERGY']) - allowed
        if unknown:
            raise ValueError('Unknown model [ENERGY] option(s): {}.'.format(', '.join(sorted(unknown))))
        for required in ('cp_c', 'cp_d', 'k_c', 'k_d', 't_sat'):
            if not model_config.has_option('ENERGY', required):
                raise ValueError("model_dir/model_config [ENERGY] requires '{}'.".format(required))

        def get(key, default=None):
            return float(model_config.get('ENERGY', key, fallback=default))

        self.cp_c, self.cp_d = get('cp_c'), get('cp_d')
        self.k_c, self.k_d = get('k_c'), get('k_d')
        self.T_sat = get('t_sat')
        self.T_backflow = get('t_backflow', self.T_sat)
        self.energy_epsilon = get('epsilon', 1e-3)
        self.interphase_heat_transfer = model_config.get('ENERGY', 'interphase_heat_transfer',
                                                         fallback='RanzMarshall').strip()
        if self.interphase_heat_transfer not in self.INTERPHASE_HEAT_TRANSFER_MODELS:
            raise ValueError("[ENERGY] interphase_heat_transfer must be one of: {}."
                             .format(', '.join(self.INTERPHASE_HEAT_TRANSFER_MODELS)))

    def _gas_sources(self) -> List:
        """ (volumetric gas source rate [1/s], dx restricted to its region) for every gas source. """
        sources = []
        if self.injection_switch and self.inj_mass_flowrate:
            sources.append((self.inj_mass_flowrate,
                            ngs.dx(definedon=self.mesh.Materials(self.injection_region))))
        return sources

    def _interphase_heat_transfer_coefficient(self, time_step: int):
        """ h_i * a_i [W/m^3/K], lagged on the Picard iterate. """
        if self.interphase_heat_transfer == 'none':
            return None
        comp = self.model_components
        ts = time_step
        wc = self.UIter.components[comp['u_c']]
        wd = self.UIter.components[comp['u_d']]
        Ad = 1 - self.UIter.components[comp['alpha_c']]
        dp, nu_c, rho_c = self.dp[ts], self.nu_c[ts], self.rho_c[ts]

        # Ranz-Marshall: Nu = 2 + 0.6 Re^1/2 Pr^1/3, interfacial area density a_i = 6 A_d / dp.
        Re = ngs.Norm(wd - wc) * dp / nu_c
        Pr = nu_c * rho_c * self.cp_c / self.k_c
        Nu = 2.0 + 0.6 * ngs.sqrt(Re) * Pr ** (1.0 / 3.0)
        a_i = 6.0 * Max(Ad, ngs.CoefficientFunction(0.0)) / dp
        return Nu * self.k_c / dp * a_i

    def _energy_phases(self, U, V, time_step: int):
        """ Per-phase quantities used by the energy forms. """
        comp = self.model_components
        ts = time_step
        Ac = self.UIter.components[comp['alpha_c']]
        return [
            # (phase, T, test, lagged fraction, wind, rho*cp, conductivity, velocity variable)
            ('c', U[comp['t_c']], V[comp['t_c']], Ac, self.UIter.components[comp['u_c']],
             self.rho_c[ts] * self.cp_c, self.k_c, 'u_c'),
            ('d', U[comp['t_d']], V[comp['t_d']], 1 - Ac, self.UIter.components[comp['u_d']],
             self.rho_d[ts] * self.cp_d, self.k_d, 'u_d'),
        ]

    # ------------------------------------------------------------------
    # Weak forms
    # ------------------------------------------------------------------

    def time_derivative_terms(self, gfu_lst: List[List[GridFunction]], scheme: str, step: int = 1):
        """ Adds the phase-fraction weighted storage terms (A_k^n + eps)(T_k - T_k^n) of the energy equations. """
        a, L = super().time_derivative_terms(gfu_lst, scheme, step)
        if scheme not in ('implicit euler', 'crank nicolson'):
            raise ValueError('TwoFluidModelEnergy only supports the implicit euler and crank nicolson schemes, '
                             'not "{}".'.format(scheme))

        U, V = self.get_trial_and_test_functions()
        comp = self.model_components
        eps = self.energy_epsilon
        Ac_old = gfu_lst[1][comp['alpha_c']]
        for name, A_old in (('t_c', Ac_old), ('t_d', 1 - Ac_old)):
            i = comp[name]
            a[0] += (A_old + eps) * U[i] * V[i]
            L[0] += (A_old + eps) * gfu_lst[1][i] * V[i]
        return a, L

    def construct_bilinear_time_ODE(self,
                                    U: Union[List[ProxyFunction], List[GridFunction]],
                                    V: List[ProxyFunction],
                                    dt: Parameter = Parameter(1.0),
                                    time_step: int = 0) -> List:
        a = super().construct_bilinear_time_ODE(U, V, dt, time_step)[0]
        n = self.n
        pen = self.penalty_interior
        eps = self.energy_epsilon
        zero = ngs.CoefficientFunction(0.0)
        phases = self._energy_phases(U, V, time_step)

        for (phase, T, s, A, w, rho_cp, k, u_var) in phases:
            # Advection A w.grad(T) = C(A T; s) - C(A; T s), with C(phi; psi) the upwind DG form of div(w phi)
            # tested with psi:  C = -(phi w.grad(psi))_K + (F(phi) jump(psi))_F,  F = upwind flux.
            # The volume terms combine to (A w.grad(T) s). Other() cannot be applied to a product of a field
            # and a trial function, so the fluxes are built from the separate traces.
            wn = w * n
            AT, AT_other = A * T, A.Other() * T.Other()
            flux_AT = 0.5 * (AT + AT_other) * wn + 0.5 * ngs.Norm(wn) * (AT - AT_other)
            flux_A = 0.5 * (A + A.Other()) * wn + 0.5 * ngs.Norm(wn) * (A - A.Other())
            a += (dt * A * (w * ngs.grad(T)) * s) * ngs.dx
            a += (dt * (flux_AT * jump(s) - flux_A * (T * s - T.Other() * s.Other()))) * ngs.dx(skeleton=True)
            open_reg = self._bc_regex('zero_stress', u_var)
            if open_reg and phase == 'c':
                # Outflow terms cancel; backflow enters as pure liquid at T_backflow (linear part in
                # construct_linear): -min(w.n, 0) (T_backflow - T) s. No gas enters (A_d = 0 in backflow).
                a += (dt * -Min(wn, zero) * T * s) * self._ds(open_reg)

            # Diffusion div((A + eps) kappa grad T), SIPG. Walls are adiabatic (natural BC).
            D = (A + eps) * (k / rho_cp)
            a += (dt * D * ngs.grad(T) * ngs.grad(s)) * ngs.dx
            a += (dt * (-(n * weighted_grad_avg(s, D)) * jump(T)
                        - (n * weighted_grad_avg(T, D)) * jump(s)
                        + avg(D) * pen * jump(T) * jump(s))) * ngs.dx(skeleton=True)

        # Gas created by the gas sources: mdot (T_sat - T_d), T_sat part in construct_linear.
        comp = self.model_components
        Td_trial, sd = U[comp['t_d']], V[comp['t_d']]
        for mdot, dx_src in self._gas_sources():
            a += (dt * mdot * Td_trial * sd) * dx_src

        # Interphase sensible heat exchange, implicit in both temperatures.
        H = self._interphase_heat_transfer_coefficient(time_step)
        if H is not None:
            (_, Tc, sc, _, _, rho_cp_c, _, _), (_, Td, sd, _, _, rho_cp_d, _, _) = phases
            a += (dt * H / rho_cp_c * (Tc - Td) * sc) * ngs.dx
            a += (dt * H / rho_cp_d * (Td - Tc) * sd) * ngs.dx

        return [a]

    def construct_linear(self,
                         V: List[ProxyFunction],
                         gfu_0: Optional[List[GridFunction]],
                         dt: Parameter,
                         time_step: int) -> List:
        L = super().construct_linear(V, gfu_0, dt, time_step)[0]
        comp = self.model_components
        n = self.n
        zero = ngs.CoefficientFunction(0.0)
        U, _ = self.get_trial_and_test_functions()

        for (phase, _, s, _, w, rho_cp, _, u_var) in self._energy_phases(U, V, time_step):
            # Backflow through open boundaries enters as pure liquid (as for alpha_c) at T_backflow.
            open_reg = self._bc_regex('zero_stress', u_var)
            if open_reg and phase == 'c':
                L += (dt * -s * self.T_backflow * Min(w * n, zero)) * self._ds(open_reg)

            # Prescribed heat fluxes [W/m^2] into the domain.
            name = 't_' + phase
            for marker, val_list in self.BC.get('neumann', {}).get(name, {}).items():
                L += (dt * val_list[time_step] / rho_cp * s) * self._ds(marker)

        # Gas created by the gas sources enters at T_sat: mdot (T_sat - T_d), T_d part in the bilinear form.
        sd = V[comp['t_d']]
        for mdot, dx_src in self._gas_sources():
            L += (dt * mdot * self.T_sat * sd) * dx_src

        return [L]
